name: CD-auto

on:
  pull_request:
    types:
      - closed

jobs:
  cd:
    uses: mihaigalos/workflows/.github/workflows/rust-cd-auto.yaml@main
    secrets:
      CARGO_API_KEY: ${{ secrets.CARGO_API_KEY }}

